// Integration-confidence: the TS codec reproduces LEZ's own bytes
// (protocol/vectors, generated by `cargo xtask vectors` from the pinned LEZ).
import { readFileSync } from 'node:fs'
import { sha256 as nobleSha256 } from '@noble/hashes/sha2.js'
import { describe, expect, it } from 'vitest'
import {
  ATA_PROGRAM,
  associatedTokenAccount,
  decodeMessage,
  decodeTransaction,
  encodeMessage,
  encodeTransaction,
  fromHex,
  messageHash,
  NATIVE_TOKEN_PROGRAM,
  nativeTransfer,
  PROGRAM_LOADER,
  type PublicMessage,
  publicAccountId,
  sendTransactionParam,
  sha256,
  TOKEN_PROGRAM,
  testimonialPost,
  toHex,
  tokenTransfer,
  transactionHash,
  utf8,
} from '../src/index.ts'
import { accountOf, publicKeyOf, signMessage, verifyHash } from '../src/sign.ts'

const vec = (f: string) =>
  JSON.parse(readFileSync(new URL(`../../../protocol/vectors/${f}`, import.meta.url), 'utf8'))
const txv = vec('public_tx.json')
const prv = vec('programs.json')

// biome-ignore lint/suspicious/noExplicitAny: vector JSON
function messageOf(f: any): PublicMessage {
  return {
    program: f.programAccountId.base58,
    // biome-ignore lint/suspicious/noExplicitAny: vector JSON
    shardSelectors: f.shardSelectors.map((s: any) => ({
      account: s.accountId.base58,
      program: s.programAccountId.base58,
    })),
    nonces: f.nonces,
    instructionData: fromHex(f.instructionData),
    fee: f.fee && {
      payer: f.fee.payer.base58,
      gasLimit: f.fee.gasLimit,
      tip: f.fee.tip,
      maxFee: f.fee.maxFee,
    },
  }
}

describe('sha256', () => {
  it('matches noble on every length around block edges', () => {
    for (let n = 0; n < 200; n++) {
      const b = new Uint8Array(n).map((_, i) => (i * 31 + n) & 255)
      expect(toHex(sha256(b))).toBe(toHex(nobleSha256(b)))
    }
  })
})

describe('public messages', () => {
  for (const m of txv.messages) {
    it(`${m.name}: borsh, hash, round trip`, () => {
      const msg = messageOf(m.fields)
      expect(toHex(encodeMessage(msg))).toBe(m.borsh)
      expect(toHex(messageHash(msg))).toBe(m.hash)
      expect(toHex(encodeMessage(decodeMessage(fromHex(m.borsh))))).toBe(m.borsh)
    })
  }
})

describe('signed native transfer', () => {
  const s = txv.signed[0]
  it('builds, signs and hashes exactly as LEZ does', () => {
    const key = fromHex(s.signingKey)
    const pub = publicKeyOf(key)
    expect(toHex(pub)).toBe(s.publicKey)
    expect(accountOf(key)).toBe(s.fields.shardSelectors[0].accountId.base58)
    expect(publicAccountId(pub)).toBe(accountOf(key))

    const call = nativeTransfer(
      accountOf(key),
      s.fields.shardSelectors[1].accountId.base58,
      s.instruction.Transfer.amount,
    )
    const msg: PublicMessage = { ...messageOf(s.fields), instructionData: call.data }
    expect(toHex(call.data)).toBe(s.fields.instructionData)
    expect(toHex(encodeMessage(msg))).toBe(s.borsh)
    expect(toHex(messageHash(msg))).toBe(s.hash)

    const tx = signMessage(msg, [key], fromHex(s.auxRand))
    expect(toHex(tx.witnesses[0]?.signature ?? new Uint8Array())).toBe(s.signature)
    expect(verifyHash(fromHex(s.signature), messageHash(msg), pub)).toBe(true)
    expect(toHex(encodeTransaction(tx))).toBe(s.transaction.borsh)
    expect(transactionHash(tx)).toBe(s.transaction.hash)
    expect(transactionHash(tx)).toBe(s.rpc.txHash)
    expect(sendTransactionParam(tx)).toBe(s.rpc.sendTransactionParam)
    expect(toHex(encodeTransaction(decodeTransaction(fromHex(s.transaction.borsh))))).toBe(
      s.transaction.borsh,
    )
  })
})

describe('programs', () => {
  it('builtin addresses', () => {
    expect(NATIVE_TOKEN_PROGRAM).toBe(prv.builtins.native)
    expect(TOKEN_PROGRAM).toBe(prv.builtins.token)
    expect(ATA_PROGRAM).toBe(prv.builtins.associatedTokenAccount)
    expect(PROGRAM_LOADER).toBe(prv.builtins.programLoader)
  })
  it('associated token account address', () => {
    const v = prv.associatedTokenAccount
    expect(associatedTokenAccount(v.owner, v.definition)).toBe(v.ata)
  })
  it('native and token transfer data', () => {
    expect(toHex(nativeTransfer('1', '1', prv.nativeTransfer.amount).data)).toBe(
      prv.nativeTransfer.data,
    )
    const t = prv.tokenTransfer
    expect(
      toHex(tokenTransfer(NATIVE_TOKEN_PROGRAM, NATIVE_TOKEN_PROGRAM, t.definition, t.amount).data),
    ).toBe(t.data)
  })
  for (const t of prv.testimonial) {
    it(`testimonial page ${t.page}: accounts and data`, () => {
      const call = testimonialPost({
        program: t.program,
        author: t.author,
        text: t.text,
        username: t.username ?? undefined,
        submission: t.submission,
        page: t.page,
        timestampMs: t.timestampMs,
      })
      expect(toHex(call.data)).toBe(t.data)
      expect(call.accounts.map((a) => a.account)).toEqual(
        [t.author, t.stats, t.record, t.previousStats].filter((x) => x !== null),
      )
      expect(call.accounts.map((a) => a.signer)).toEqual(call.accounts.map((_, i) => i === 0))
    })
  }
  it('utf8 matches the platform encoder', () => {
    const s = 'I use Logos Kit ✓\n😀 é'
    expect(toHex(utf8(s))).toBe(toHex(new TextEncoder().encode(s)))
  })
})
