//! `cargo xtask types`: Rust types for LWS-0, generated with typify from the
//! canonical `protocol/schema/lws0.schema.json` (which the TypeBox sources
//! emit). CI regenerates and diffs, so Rust and TS can't drift.

use std::{fs, path::Path};

use anyhow::{Context as _, Result};
use typify::{TypeSpace, TypeSpaceSettings};

pub fn run(repo_root: &Path) -> Result<()> {
    let root = repo_root.canonicalize()?;
    let schema_path = root.join("protocol/schema/lws0.schema.json");
    let schema: schemars::schema::RootSchema =
        serde_json::from_str(&fs::read_to_string(&schema_path)?).context("parse LWS-0 schema")?;

    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(false);
    let mut space = TypeSpace::new(&settings);
    space.add_root_schema(schema).context("typify conversion")?;

    let file: syn::File = syn::parse2(space.to_stream()).context("parse generated tokens")?;
    let body = prettyplease::unparse(&file);
    let out = format!(
        "// @generated by `cargo xtask types` from protocol/schema/lws0.schema.json. Do not edit.\n\n{body}"
    );
    let dest = root.join("crates/lwsp-types/src/generated.rs");
    fs::write(&dest, out).with_context(|| format!("write {}", dest.display()))?;
    // rustfmt (pinned via rust-toolchain.toml) is the canonical layout, so the
    // file passes `cargo fmt --check` and regenerating is a no-op diff.
    let status = std::process::Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&dest)
        .status()
        .context("run rustfmt")?;
    anyhow::ensure!(status.success(), "rustfmt failed on {}", dest.display());
    println!("wrote {}", dest.display());
    Ok(())
}
