// @logos-kit/theme: the Tray design tokens (D14, docs/design/brand.md), light
// and dark, for web/React Native (CSS variables) and QML (`toQmlTokens`).
// QML-safe (ES2017).

export interface Tokens {
  bg: string
  surface: string
  surface2: string
  line: string
  text: string
  text2: string
  text3: string
  /** Only for private state. */
  private: string
  privateSoft: string
  privateText: string
  /** Public / neutral actions. */
  action: string
  actionText: string
  ok: string
  warn: string
  danger: string
  island: string
  font: string
  numFont: string
  monoFont: string
  rSheet: number
  rCard: number
  rBtn: number
  rRow: number
  scheme: 'dark' | 'light'
}

export const trayLight: Tokens = {
  bg: '#ebebef',
  surface: '#ffffff',
  surface2: '#f3f3f6',
  line: 'rgba(14,14,18,0.07)',
  text: '#0e0e12',
  text2: '#6c6c78',
  text3: '#a2a2ad',
  private: '#6b5fff',
  privateSoft: 'rgba(107,95,255,0.12)',
  privateText: '#5145e6',
  action: '#1f7bff',
  actionText: '#ffffff',
  ok: '#12a150',
  warn: '#d49a00',
  danger: '#e5484d',
  island: '#0e0e12',
  font: '"Onest", ui-sans-serif, sans-serif',
  numFont: '"Onest", ui-sans-serif, sans-serif',
  monoFont: '"JetBrains Mono", ui-monospace, monospace',
  rSheet: 36,
  rCard: 26,
  rBtn: 999,
  rRow: 20,
  scheme: 'light',
}

export const trayDark: Tokens = {
  bg: '#000000',
  surface: '#161618',
  surface2: '#202023',
  line: 'rgba(255,255,255,0.07)',
  text: '#f4f4f6',
  text2: '#9a9aa5',
  text3: '#5f5f69',
  private: '#7a70ff',
  privateSoft: 'rgba(122,112,255,0.18)',
  privateText: '#c4bfff',
  action: '#3898ff',
  actionText: '#ffffff',
  ok: '#4bd166',
  warn: '#ffd641',
  danger: '#ff6257',
  island: '#000000',
  font: trayLight.font,
  numFont: trayLight.numFont,
  monoFont: trayLight.monoFont,
  rSheet: trayLight.rSheet,
  rCard: trayLight.rCard,
  rBtn: trayLight.rBtn,
  rRow: trayLight.rRow,
  scheme: 'dark',
}

export const themes: { light: Tokens; dark: Tokens } = { light: trayLight, dark: trayDark }

export function cssVars(t: Tokens): Record<string, string> {
  return {
    '--bg': t.bg,
    '--surface': t.surface,
    '--surface2': t.surface2,
    '--line': t.line,
    '--text': t.text,
    '--text2': t.text2,
    '--text3': t.text3,
    '--private': t.private,
    '--private-soft': t.privateSoft,
    '--private-text': t.privateText,
    '--action': t.action,
    '--action-text': t.actionText,
    '--ok': t.ok,
    '--warn': t.warn,
    '--danger': t.danger,
    '--island': t.island,
    '--font': t.font,
    '--num': t.numFont,
    '--mono': t.monoFont,
    '--r-sheet': `${t.rSheet}px`,
    '--r-card': `${t.rCard}px`,
    '--r-btn': `${t.rBtn}px`,
    '--r-row': `${t.rRow}px`,
    colorScheme: t.scheme,
  }
}

const hex2 = (n: number): string => {
  const s = Math.max(0, Math.min(255, Math.round(n))).toString(16)
  return s.length < 2 ? `0${s}` : s
}

/** A CSS colour (`#rgb`, `#rrggbb`, `rgba()`) as QML's `#AARRGGBB` / `#RRGGBB`. */
export function qmlColor(css: string): string {
  const c = css.trim().toLowerCase()
  if (/^#[0-9a-f]{6}$/.test(c)) return c
  if (/^#[0-9a-f]{3}$/.test(c)) return `#${c[1]}${c[1]}${c[2]}${c[2]}${c[3]}${c[3]}`
  const m = /^rgba?\(\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*(?:,\s*([0-9.]+)\s*)?\)$/.exec(
    c,
  )
  if (!m) throw new Error(`not a colour QML can use: ${css}`)
  const a = m[4] === undefined ? 1 : Number(m[4])
  return `#${hex2(a * 255)}${hex2(Number(m[1]))}${hex2(Number(m[2]))}${hex2(Number(m[3]))}`
}

/** The first family of a CSS font stack (QML's `font.family` takes one). */
export const qmlFont = (stack: string): string =>
  (stack.split(',')[0] as string).trim().replace(/^["']|["']$/g, '')

export interface QmlTokens {
  [key: string]: string | number | boolean
}

/** Tokens for QML: colours as `#AARRGGBB`, one font family, radii as numbers. */
export function toQmlTokens(t: Tokens): QmlTokens {
  const out: QmlTokens = {}
  for (const k of Object.keys(t) as (keyof Tokens)[]) {
    const v = t[k]
    if (k === 'font' || k === 'numFont' || k === 'monoFont') out[k] = qmlFont(v as string)
    else if (k === 'scheme') out.dark = v === 'dark'
    else if (typeof v === 'number') out[k] = v
    else out[k] = qmlColor(v as string)
  }
  return out
}

/** `Tokens.js` for a QML import (`import "Tokens.js" as Tokens` → `Tokens.dark.bg`). */
export function qmlTokensModule(): string {
  const body = (['light', 'dark'] as const)
    .map((k) => `var ${k} = ${JSON.stringify(toQmlTokens(themes[k]), null, 2)};`)
    .join('\n')
  return `.pragma library\n// Generated by @logos-kit/theme (Tray, docs/design/brand.md). Do not edit.\n${body}\n`
}
