// @generated by `cargo xtask types` from protocol/schema/lws0.schema.json. Do not edit.

///Base58-encoded 32-byte LEZ account id
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct AccountId(::std::string::String);
impl ::std::ops::Deref for AccountId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<AccountId> for ::std::string::String {
    fn from(value: AccountId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for AccountId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^[1-9A-HJ-NP-Za-km-z]{32,44}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[1-9A-HJ-NP-Za-km-z]{32,44}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for AccountId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AccountId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for AccountId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`AccountKind`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AccountKind {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "private")]
    Private,
}
impl ::std::fmt::Display for AccountKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Public => f.write_str("public"),
            Self::Private => f.write_str("private"),
        }
    }
}
impl ::std::str::FromStr for AccountKind {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "public" => Ok(Self::Public),
            "private" => Ok(Self::Private),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AccountKind {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AccountKind {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`AccountRef`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
pub struct AccountRef {
    #[serde(flatten, skip_serializing_if = "::std::option::Option::is_none")]
    pub subtype_0: ::std::option::Option<AccountId>,
    #[serde(flatten, skip_serializing_if = "::std::option::Option::is_none")]
    pub subtype_1: ::std::option::Option<PrivateHandle>,
}
///`BalanceParams`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct BalanceParams {
    pub account: AccountRef,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub asset: ::std::option::Option<AccountId>,
    pub chain: ChainId,
}
///`BalanceResult`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct BalanceResult {
    pub amount: U128,
    #[serde(
        rename = "asOfBlock",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub as_of_block: ::std::option::Option<BalanceResultAsOfBlock>,
    pub asset: BalanceResultAsset,
    pub synced: bool,
}
///`BalanceResultAsOfBlock`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct BalanceResultAsOfBlock(::std::string::String);
impl ::std::ops::Deref for BalanceResultAsOfBlock {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<BalanceResultAsOfBlock> for ::std::string::String {
    fn from(value: BalanceResultAsOfBlock) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for BalanceResultAsOfBlock {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^[0-9]+$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[0-9]+$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for BalanceResultAsOfBlock {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for BalanceResultAsOfBlock {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for BalanceResultAsOfBlock {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`BalanceResultAsset`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
pub struct BalanceResultAsset {
    #[serde(flatten, skip_serializing_if = "::std::option::Option::is_none")]
    pub subtype_0: ::std::option::Option<::std::string::String>,
    #[serde(flatten, skip_serializing_if = "::std::option::Option::is_none")]
    pub subtype_1: ::std::option::Option<AccountId>,
}
///`Base64`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct Base64(::std::string::String);
impl ::std::ops::Deref for Base64 {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<Base64> for ::std::string::String {
    fn from(value: Base64) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for Base64 {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 65000usize {
            return Err("longer than 65000 characters".into());
        }
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^[A-Za-z0-9+/]*={0,2}$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[A-Za-z0-9+/]*={0,2}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for Base64 {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Base64 {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for Base64 {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`Capabilities`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Capabilities {
    #[serde(rename = "accountKinds")]
    pub account_kinds: ::std::vec::Vec<AccountKind>,
    pub batch: CapabilitiesBatch,
    #[serde(rename = "outcomeVerification")]
    pub outcome_verification: ::std::vec::Vec<CapabilitiesOutcomeVerificationItem>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub proving: ::std::option::Option<CapabilitiesProving>,
    #[serde(rename = "requestFunds")]
    pub request_funds: bool,
    #[serde(rename = "signIn")]
    pub sign_in: bool,
    #[serde(rename = "signMessage")]
    pub sign_message: bool,
    #[serde(rename = "signTransaction")]
    pub sign_transaction: bool,
}
///`CapabilitiesBatch`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CapabilitiesBatch {
    pub atomic: CapabilitiesBatchAtomic,
    #[serde(rename = "maxInstructions")]
    pub max_instructions: ::std::num::NonZeroU64,
}
///`CapabilitiesBatchAtomic`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum CapabilitiesBatchAtomic {
    #[serde(rename = "supported")]
    Supported,
    #[serde(rename = "unsupported")]
    Unsupported,
}
impl ::std::fmt::Display for CapabilitiesBatchAtomic {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Supported => f.write_str("supported"),
            Self::Unsupported => f.write_str("unsupported"),
        }
    }
}
impl ::std::str::FromStr for CapabilitiesBatchAtomic {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "supported" => Ok(Self::Supported),
            "unsupported" => Ok(Self::Unsupported),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for CapabilitiesBatchAtomic {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for CapabilitiesBatchAtomic {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`CapabilitiesOutcomeVerificationItem`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum CapabilitiesOutcomeVerificationItem {
    #[serde(rename = "own-account-invariant")]
    OwnAccountInvariant,
    #[serde(rename = "program-event")]
    ProgramEvent,
    #[serde(rename = "node")]
    Node,
}
impl ::std::fmt::Display for CapabilitiesOutcomeVerificationItem {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::OwnAccountInvariant => f.write_str("own-account-invariant"),
            Self::ProgramEvent => f.write_str("program-event"),
            Self::Node => f.write_str("node"),
        }
    }
}
impl ::std::str::FromStr for CapabilitiesOutcomeVerificationItem {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "own-account-invariant" => Ok(Self::OwnAccountInvariant),
            "program-event" => Ok(Self::ProgramEvent),
            "node" => Ok(Self::Node),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for CapabilitiesOutcomeVerificationItem {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for CapabilitiesOutcomeVerificationItem {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`CapabilitiesProving`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CapabilitiesProving {
    pub location: CapabilitiesProvingLocation,
    #[serde(
        rename = "typicalSeconds",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub typical_seconds: ::std::option::Option<u64>,
}
///`CapabilitiesProvingLocation`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum CapabilitiesProvingLocation {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "paired")]
    Paired,
    #[serde(rename = "user-owned")]
    UserOwned,
    #[serde(rename = "tee")]
    Tee,
}
impl ::std::fmt::Display for CapabilitiesProvingLocation {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Local => f.write_str("local"),
            Self::Paired => f.write_str("paired"),
            Self::UserOwned => f.write_str("user-owned"),
            Self::Tee => f.write_str("tee"),
        }
    }
}
impl ::std::str::FromStr for CapabilitiesProvingLocation {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "local" => Ok(Self::Local),
            "paired" => Ok(Self::Paired),
            "user-owned" => Ok(Self::UserOwned),
            "tee" => Ok(Self::Tee),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for CapabilitiesProvingLocation {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for CapabilitiesProvingLocation {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`Capability`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum Capability {
    #[serde(rename = "accounts")]
    Accounts,
    #[serde(rename = "read_public")]
    ReadPublic,
    #[serde(rename = "read_private")]
    ReadPrivate,
    #[serde(rename = "propose_tx")]
    ProposeTx,
    #[serde(rename = "sign_message")]
    SignMessage,
    #[serde(rename = "request_proof")]
    RequestProof,
}
impl ::std::fmt::Display for Capability {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Accounts => f.write_str("accounts"),
            Self::ReadPublic => f.write_str("read_public"),
            Self::ReadPrivate => f.write_str("read_private"),
            Self::ProposeTx => f.write_str("propose_tx"),
            Self::SignMessage => f.write_str("sign_message"),
            Self::RequestProof => f.write_str("request_proof"),
        }
    }
}
impl ::std::str::FromStr for Capability {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "accounts" => Ok(Self::Accounts),
            "read_public" => Ok(Self::ReadPublic),
            "read_private" => Ok(Self::ReadPrivate),
            "propose_tx" => Ok(Self::ProposeTx),
            "sign_message" => Ok(Self::SignMessage),
            "request_proof" => Ok(Self::RequestProof),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Capability {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Capability {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///CAIP-2 chain id, e.g. "lez:testnet"
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct ChainId(::std::string::String);
impl ::std::ops::Deref for ChainId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<ChainId> for ::std::string::String {
    fn from(value: ChainId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for ChainId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^[-a-z0-9]{3,8}:[-_a-zA-Z0-9]{1,32}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[-a-z0-9]{3,8}:[-_a-zA-Z0-9]{1,32}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for ChainId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ChainId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for ChainId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`ConnectParams`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ConnectParams {
    #[serde(
        rename = "accountKinds",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub account_kinds: ::std::vec::Vec<AccountKind>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<Capability>,
    pub chains: ::std::vec::Vec<ChainId>,
    #[serde(
        rename = "signIn",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub sign_in: ::std::option::Option<SignInRequest>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub silent: ::std::option::Option<bool>,
}
///`Effect`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Effect {
    pub account: AccountRef,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub after: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub asset: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub before: ::std::option::Option<::std::string::String>,
    pub field: EffectField,
}
///`EffectField`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum EffectField {
    #[serde(rename = "balance")]
    Balance,
    #[serde(rename = "token_balance")]
    TokenBalance,
    #[serde(rename = "data")]
    Data,
    #[serde(rename = "authority")]
    Authority,
    #[serde(rename = "nonce")]
    Nonce,
}
impl ::std::fmt::Display for EffectField {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Balance => f.write_str("balance"),
            Self::TokenBalance => f.write_str("token_balance"),
            Self::Data => f.write_str("data"),
            Self::Authority => f.write_str("authority"),
            Self::Nonce => f.write_str("nonce"),
        }
    }
}
impl ::std::str::FromStr for EffectField {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "balance" => Ok(Self::Balance),
            "token_balance" => Ok(Self::TokenBalance),
            "data" => Ok(Self::Data),
            "authority" => Ok(Self::Authority),
            "nonce" => Ok(Self::Nonce),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for EffectField {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for EffectField {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`FeeInfo`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
pub struct FeeInfo {
    #[serde(
        rename = "estimatedMax",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub estimated_max: ::std::option::Option<U128>,
    #[serde(
        rename = "gasLimit",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub gas_limit: ::std::option::Option<FeeInfoGasLimit>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub used: ::std::option::Option<U128>,
}
///`FeeInfoGasLimit`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct FeeInfoGasLimit(::std::string::String);
impl ::std::ops::Deref for FeeInfoGasLimit {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<FeeInfoGasLimit> for ::std::string::String {
    fn from(value: FeeInfoGasLimit) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for FeeInfoGasLimit {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^[0-9]+$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[0-9]+$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for FeeInfoGasLimit {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for FeeInfoGasLimit {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for FeeInfoGasLimit {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`Hash32`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct Hash32(::std::string::String);
impl ::std::ops::Deref for Hash32 {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<Hash32> for ::std::string::String {
    fn from(value: Hash32) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for Hash32 {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^0x[0-9a-f]{64}$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^0x[0-9a-f]{64}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for Hash32 {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Hash32 {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for Hash32 {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`Hex`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct Hex(::std::string::String);
impl ::std::ops::Deref for Hex {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<Hex> for ::std::string::String {
    fn from(value: Hex) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for Hex {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^0x[0-9a-f]*$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^0x[0-9a-f]*$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for Hex {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Hex {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for Hex {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`Instruction`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Instruction {
    pub accounts: ::std::vec::Vec<InstructionAccountsItem>,
    pub data: Base64,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub display: ::std::option::Option<InstructionDisplay>,
    pub program: AccountId,
}
///`InstructionAccountsItem`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct InstructionAccountsItem {
    pub account: AccountRef,
    pub signer: bool,
    pub writable: bool,
}
///`InstructionDisplay`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
pub struct InstructionDisplay {
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
    )]
    pub args: ::std::collections::HashMap<InstructionDisplayArgsKey, ::serde_json::Value>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub method: ::std::option::Option<InstructionDisplayMethod>,
}
///`InstructionDisplayArgsKey`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct InstructionDisplayArgsKey(::std::string::String);
impl ::std::ops::Deref for InstructionDisplayArgsKey {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<InstructionDisplayArgsKey> for ::std::string::String {
    fn from(value: InstructionDisplayArgsKey) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for InstructionDisplayArgsKey {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^.*$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^.*$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for InstructionDisplayArgsKey {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for InstructionDisplayArgsKey {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for InstructionDisplayArgsKey {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`InstructionDisplayMethod`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct InstructionDisplayMethod(::std::string::String);
impl ::std::ops::Deref for InstructionDisplayMethod {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<InstructionDisplayMethod> for ::std::string::String {
    fn from(value: InstructionDisplayMethod) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for InstructionDisplayMethod {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 64usize {
            return Err("longer than 64 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for InstructionDisplayMethod {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for InstructionDisplayMethod {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for InstructionDisplayMethod {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`Lifecycle`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum Lifecycle {
    #[serde(rename = "awaiting_approval")]
    AwaitingApproval,
    #[serde(rename = "building")]
    Building,
    #[serde(rename = "proving")]
    Proving,
    #[serde(rename = "signing")]
    Signing,
    #[serde(rename = "submitted")]
    Submitted,
    #[serde(rename = "included")]
    Included,
    #[serde(rename = "finalized")]
    Finalized,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "dropped")]
    Dropped,
    #[serde(rename = "expired")]
    Expired,
}
impl ::std::fmt::Display for Lifecycle {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::AwaitingApproval => f.write_str("awaiting_approval"),
            Self::Building => f.write_str("building"),
            Self::Proving => f.write_str("proving"),
            Self::Signing => f.write_str("signing"),
            Self::Submitted => f.write_str("submitted"),
            Self::Included => f.write_str("included"),
            Self::Finalized => f.write_str("finalized"),
            Self::Rejected => f.write_str("rejected"),
            Self::Dropped => f.write_str("dropped"),
            Self::Expired => f.write_str("expired"),
        }
    }
}
impl ::std::str::FromStr for Lifecycle {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "awaiting_approval" => Ok(Self::AwaitingApproval),
            "building" => Ok(Self::Building),
            "proving" => Ok(Self::Proving),
            "signing" => Ok(Self::Signing),
            "submitted" => Ok(Self::Submitted),
            "included" => Ok(Self::Included),
            "finalized" => Ok(Self::Finalized),
            "rejected" => Ok(Self::Rejected),
            "dropped" => Ok(Self::Dropped),
            "expired" => Ok(Self::Expired),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Lifecycle {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Lifecycle {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`Lws0LogosKitWalletProtocol`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct Lws0LogosKitWalletProtocol(pub ::serde_json::Value);
impl ::std::ops::Deref for Lws0LogosKitWalletProtocol {
    type Target = ::serde_json::Value;
    fn deref(&self) -> &::serde_json::Value {
        &self.0
    }
}
impl ::std::convert::From<Lws0LogosKitWalletProtocol> for ::serde_json::Value {
    fn from(value: Lws0LogosKitWalletProtocol) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Value> for Lws0LogosKitWalletProtocol {
    fn from(value: ::serde_json::Value) -> Self {
        Self(value)
    }
}
///`Outcome`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum Outcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "unknown")]
    Unknown,
}
impl ::std::fmt::Display for Outcome {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Success => f.write_str("success"),
            Self::Failure => f.write_str("failure"),
            Self::Unknown => f.write_str("unknown"),
        }
    }
}
impl ::std::str::FromStr for Outcome {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "success" => Ok(Self::Success),
            "failure" => Ok(Self::Failure),
            "unknown" => Ok(Self::Unknown),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Outcome {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Outcome {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`OutcomeSource`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum OutcomeSource {
    #[serde(rename = "own-account-invariant")]
    OwnAccountInvariant,
    #[serde(rename = "program-event")]
    ProgramEvent,
    #[serde(rename = "node")]
    Node,
    #[serde(rename = "none")]
    None,
}
impl ::std::fmt::Display for OutcomeSource {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::OwnAccountInvariant => f.write_str("own-account-invariant"),
            Self::ProgramEvent => f.write_str("program-event"),
            Self::Node => f.write_str("node"),
            Self::None => f.write_str("none"),
        }
    }
}
impl ::std::str::FromStr for OutcomeSource {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "own-account-invariant" => Ok(Self::OwnAccountInvariant),
            "program-event" => Ok(Self::ProgramEvent),
            "node" => Ok(Self::Node),
            "none" => Ok(Self::None),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for OutcomeSource {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for OutcomeSource {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Opaque per-origin private account handle
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct PrivateHandle(::std::string::String);
impl ::std::ops::Deref for PrivateHandle {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<PrivateHandle> for ::std::string::String {
    fn from(value: PrivateHandle) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for PrivateHandle {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| {
                ::regress::Regex::new("^pvt_[A-Za-z0-9_-]{16,64}$").unwrap()
            });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^pvt_[A-Za-z0-9_-]{16,64}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for PrivateHandle {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for PrivateHandle {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for PrivateHandle {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`ReadAccountParams`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ReadAccountParams {
    pub account: AccountId,
    pub chain: ChainId,
    pub program: AccountId,
}
///`ReadAccountResult`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ReadAccountResult {
    pub data: Base64,
    pub nonce: U128,
}
///`RequestFundsParams`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct RequestFundsParams {
    pub account: AccountRef,
    pub chain: ChainId,
}
///`RequestFundsResult`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct RequestFundsResult {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub amount: ::std::option::Option<U128>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub reason: ::std::option::Option<RequestFundsResultReason>,
    #[serde(
        rename = "retryAfterSeconds",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub retry_after_seconds: ::std::option::Option<u64>,
    #[serde(
        rename = "shieldHandle",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub shield_handle: ::std::option::Option<::std::string::String>,
    pub status: RequestFundsResultStatus,
    #[serde(
        rename = "txHash",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tx_hash: ::std::option::Option<Hash32>,
}
///`RequestFundsResultReason`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct RequestFundsResultReason(::std::string::String);
impl ::std::ops::Deref for RequestFundsResultReason {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<RequestFundsResultReason> for ::std::string::String {
    fn from(value: RequestFundsResultReason) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for RequestFundsResultReason {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 256usize {
            return Err("longer than 256 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for RequestFundsResultReason {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RequestFundsResultReason {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for RequestFundsResultReason {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`RequestFundsResultStatus`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum RequestFundsResultStatus {
    #[serde(rename = "funded")]
    Funded,
    #[serde(rename = "rate_limited")]
    RateLimited,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "outcome_unknown")]
    OutcomeUnknown,
}
impl ::std::fmt::Display for RequestFundsResultStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Funded => f.write_str("funded"),
            Self::RateLimited => f.write_str("rate_limited"),
            Self::Rejected => f.write_str("rejected"),
            Self::OutcomeUnknown => f.write_str("outcome_unknown"),
        }
    }
}
impl ::std::str::FromStr for RequestFundsResultStatus {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "funded" => Ok(Self::Funded),
            "rate_limited" => Ok(Self::RateLimited),
            "rejected" => Ok(Self::Rejected),
            "outcome_unknown" => Ok(Self::OutcomeUnknown),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for RequestFundsResultStatus {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RequestFundsResultStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`Session`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Session {
    pub accounts: ::std::vec::Vec<WalletAccount>,
    pub capabilities: Capabilities,
    pub chains: ::std::vec::Vec<ChainId>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub expiry: ::std::option::Option<Timestamp>,
    pub origin: ::std::string::String,
    #[serde(rename = "sessionId")]
    pub session_id: SessionSessionId,
    #[serde(
        rename = "signIn",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub sign_in: ::std::option::Option<SignInResult>,
}
///`SessionSessionId`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SessionSessionId(::std::string::String);
impl ::std::ops::Deref for SessionSessionId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SessionSessionId> for ::std::string::String {
    fn from(value: SessionSessionId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SessionSessionId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 128usize {
            return Err("longer than 128 characters".into());
        }
        if value.chars().count() < 16usize {
            return Err("shorter than 16 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SessionSessionId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SessionSessionId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SessionSessionId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`SignInRequest`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct SignInRequest {
    pub domain: SignInRequestDomain,
    #[serde(
        rename = "expirationTime",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub expiration_time: ::std::option::Option<Timestamp>,
    #[serde(rename = "issuedAt")]
    pub issued_at: Timestamp,
    pub nonce: SignInRequestNonce,
    #[serde(
        rename = "notBefore",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub not_before: ::std::option::Option<Timestamp>,
    #[serde(
        rename = "requestId",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub request_id: ::std::option::Option<SignInRequestRequestId>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub statement: ::std::option::Option<SignInRequestStatement>,
    pub uri: SignInRequestUri,
}
///`SignInRequestDomain`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SignInRequestDomain(::std::string::String);
impl ::std::ops::Deref for SignInRequestDomain {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SignInRequestDomain> for ::std::string::String {
    fn from(value: SignInRequestDomain) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SignInRequestDomain {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 253usize {
            return Err("longer than 253 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SignInRequestDomain {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SignInRequestDomain {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SignInRequestDomain {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`SignInRequestNonce`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SignInRequestNonce(::std::string::String);
impl ::std::ops::Deref for SignInRequestNonce {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SignInRequestNonce> for ::std::string::String {
    fn from(value: SignInRequestNonce) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SignInRequestNonce {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 64usize {
            return Err("longer than 64 characters".into());
        }
        if value.chars().count() < 8usize {
            return Err("shorter than 8 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SignInRequestNonce {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SignInRequestNonce {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SignInRequestNonce {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`SignInRequestRequestId`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SignInRequestRequestId(::std::string::String);
impl ::std::ops::Deref for SignInRequestRequestId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SignInRequestRequestId> for ::std::string::String {
    fn from(value: SignInRequestRequestId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SignInRequestRequestId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 64usize {
            return Err("longer than 64 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SignInRequestRequestId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SignInRequestRequestId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SignInRequestRequestId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`SignInRequestStatement`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SignInRequestStatement(::std::string::String);
impl ::std::ops::Deref for SignInRequestStatement {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SignInRequestStatement> for ::std::string::String {
    fn from(value: SignInRequestStatement) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SignInRequestStatement {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 512usize {
            return Err("longer than 512 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SignInRequestStatement {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SignInRequestStatement {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SignInRequestStatement {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`SignInRequestUri`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SignInRequestUri(::std::string::String);
impl ::std::ops::Deref for SignInRequestUri {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SignInRequestUri> for ::std::string::String {
    fn from(value: SignInRequestUri) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SignInRequestUri {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 2048usize {
            return Err("longer than 2048 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SignInRequestUri {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SignInRequestUri {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SignInRequestUri {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`SignInResult`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct SignInResult {
    pub account: WalletAccount,
    pub signature: Base64,
    #[serde(rename = "signedMessage")]
    pub signed_message: ::std::string::String,
}
///`SignMessageParams`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct SignMessageParams {
    pub account: AccountId,
    pub message: Base64,
}
///`SignMessageResult`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct SignMessageResult {
    #[serde(rename = "publicKey")]
    pub public_key: Base64,
    pub signature: Base64,
    pub tag: ::std::string::String,
}
///`SubmitResult`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct SubmitResult {
    pub handle: SubmitResultHandle,
    #[serde(
        rename = "txHash",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tx_hash: ::std::option::Option<Hash32>,
}
///`SubmitResultHandle`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct SubmitResultHandle(::std::string::String);
impl ::std::ops::Deref for SubmitResultHandle {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<SubmitResultHandle> for ::std::string::String {
    fn from(value: SubmitResultHandle) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for SubmitResultHandle {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 128usize {
            return Err("longer than 128 characters".into());
        }
        if value.chars().count() < 16usize {
            return Err("shorter than 16 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for SubmitResultHandle {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for SubmitResultHandle {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for SubmitResultHandle {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`Timestamp`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct Timestamp(pub ::chrono::DateTime<::chrono::offset::Utc>);
impl ::std::ops::Deref for Timestamp {
    type Target = ::chrono::DateTime<::chrono::offset::Utc>;
    fn deref(&self) -> &::chrono::DateTime<::chrono::offset::Utc> {
        &self.0
    }
}
impl ::std::convert::From<Timestamp> for ::chrono::DateTime<::chrono::offset::Utc> {
    fn from(value: Timestamp) -> Self {
        value.0
    }
}
impl ::std::convert::From<::chrono::DateTime<::chrono::offset::Utc>> for Timestamp {
    fn from(value: ::chrono::DateTime<::chrono::offset::Utc>) -> Self {
        Self(value)
    }
}
impl ::std::fmt::Display for Timestamp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        self.0.fmt(f)
    }
}
impl ::std::str::FromStr for Timestamp {
    type Err = <::chrono::DateTime<::chrono::offset::Utc> as ::std::str::FromStr>::Err;
    fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
        Ok(Self(value.parse()?))
    }
}
impl ::std::convert::TryFrom<&str> for Timestamp {
    type Error = <::chrono::DateTime<::chrono::offset::Utc> as ::std::str::FromStr>::Err;
    fn try_from(value: &str) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<String> for Timestamp {
    type Error = <::chrono::DateTime<::chrono::offset::Utc> as ::std::str::FromStr>::Err;
    fn try_from(value: String) -> ::std::result::Result<Self, Self::Error> {
        value.parse()
    }
}
///`TransactionProposal`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct TransactionProposal {
    pub account: AccountRef,
    #[serde(
        rename = "atomicRequired",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub atomic_required: ::std::option::Option<bool>,
    pub chain: ChainId,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub id: ::std::option::Option<TransactionProposalId>,
    pub instructions: ::std::vec::Vec<Instruction>,
}
///`TransactionProposalId`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct TransactionProposalId(::std::string::String);
impl ::std::ops::Deref for TransactionProposalId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<TransactionProposalId> for ::std::string::String {
    fn from(value: TransactionProposalId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for TransactionProposalId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 64usize {
            return Err("longer than 64 characters".into());
        }
        if value.chars().count() < 1usize {
            return Err("shorter than 1 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for TransactionProposalId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for TransactionProposalId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for TransactionProposalId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`TransactionStatus`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct TransactionStatus {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub block: ::std::option::Option<TransactionStatusBlock>,
    pub chain: ChainId,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub error: ::std::option::Option<TransactionStatusError>,
    #[serde(
        rename = "expectedEffects",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub expected_effects: ::std::vec::Vec<Effect>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub fee: ::std::option::Option<FeeInfo>,
    pub handle: ::std::string::String,
    pub lifecycle: Lifecycle,
    #[serde(
        rename = "observedEffects",
        default,
        skip_serializing_if = "::std::vec::Vec::is_empty"
    )]
    pub observed_effects: ::std::vec::Vec<Effect>,
    pub outcome: Outcome,
    #[serde(rename = "outcomeSource")]
    pub outcome_source: OutcomeSource,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub proving: ::std::option::Option<TransactionStatusProving>,
    #[serde(
        rename = "txHash",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tx_hash: ::std::option::Option<Hash32>,
}
///`TransactionStatusBlock`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct TransactionStatusBlock {
    pub id: TransactionStatusBlockId,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub timestamp: ::std::option::Option<Timestamp>,
}
///`TransactionStatusBlockId`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct TransactionStatusBlockId(::std::string::String);
impl ::std::ops::Deref for TransactionStatusBlockId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<TransactionStatusBlockId> for ::std::string::String {
    fn from(value: TransactionStatusBlockId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for TransactionStatusBlockId {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^[0-9]+$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[0-9]+$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for TransactionStatusBlockId {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for TransactionStatusBlockId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for TransactionStatusBlockId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`TransactionStatusError`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct TransactionStatusError {
    pub code: i64,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub data: ::std::option::Option<::serde_json::Value>,
    pub message: ::std::string::String,
}
///`TransactionStatusProving`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct TransactionStatusProving {
    #[serde(
        rename = "etaSeconds",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub eta_seconds: ::std::option::Option<u64>,
    pub phase: TransactionStatusProvingPhase,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub progress: ::std::option::Option<f64>,
    #[serde(
        rename = "startedAt",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub started_at: ::std::option::Option<Timestamp>,
}
///`TransactionStatusProvingPhase`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum TransactionStatusProvingPhase {
    #[serde(rename = "preparing")]
    Preparing,
    #[serde(rename = "proving")]
    Proving,
    #[serde(rename = "submitting")]
    Submitting,
    #[serde(rename = "waiting_for_block")]
    WaitingForBlock,
}
impl ::std::fmt::Display for TransactionStatusProvingPhase {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Preparing => f.write_str("preparing"),
            Self::Proving => f.write_str("proving"),
            Self::Submitting => f.write_str("submitting"),
            Self::WaitingForBlock => f.write_str("waiting_for_block"),
        }
    }
}
impl ::std::str::FromStr for TransactionStatusProvingPhase {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "preparing" => Ok(Self::Preparing),
            "proving" => Ok(Self::Proving),
            "submitting" => Ok(Self::Submitting),
            "waiting_for_block" => Ok(Self::WaitingForBlock),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for TransactionStatusProvingPhase {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for TransactionStatusProvingPhase {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///u128 as a decimal string. The pattern allows up to 39 digits; values above 2^128-1 are rejected by the codec and wallet with -32602.
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct U128(::std::string::String);
impl ::std::ops::Deref for U128 {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<U128> for ::std::string::String {
    fn from(value: U128) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for U128 {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
            ::std::sync::LazyLock::new(|| ::regress::Regex::new("^(0|[1-9][0-9]{0,38})$").unwrap());
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^(0|[1-9][0-9]{0,38})$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for U128 {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for U128 {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for U128 {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`WalletAccount`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct WalletAccount {
    pub address: AccountRef,
    pub capabilities: ::std::vec::Vec<Capability>,
    pub chain: ChainId,
    pub kind: AccountKind,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub label: ::std::option::Option<WalletAccountLabel>,
    #[serde(
        rename = "publicKey",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub public_key: ::std::option::Option<Base64>,
}
///`WalletAccountLabel`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct WalletAccountLabel(::std::string::String);
impl ::std::ops::Deref for WalletAccountLabel {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<WalletAccountLabel> for ::std::string::String {
    fn from(value: WalletAccountLabel) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for WalletAccountLabel {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        if value.chars().count() > 64usize {
            return Err("longer than 64 characters".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for WalletAccountLabel {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for WalletAccountLabel {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for WalletAccountLabel {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
